# Generated by Django 5.2.7 on 2025-12-03 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '0002_alter_reservation_mode_paiement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FidelityTierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], max_length=20, unique=True)),
                ('points_requis_min', models.PositiveIntegerField()),
                ('points_requis_max', models.PositiveIntegerField()),
                ('pourcentage_remise', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bonus_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicateur de points', max_digits=3)),
            ],
            options={
                'ordering': ['points_requis_min'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('tier', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='BRONZE', max_length=10)),
                ('totalEarnedPoints', models.PositiveIntegerField(default=0)),
                ('totalRedeemedPoints', models.PositiveIntegerField(default=0)),
                ('pointsExpiryDate', models.DateTimeField(blank=True, null=True)),
                ('last_tier_update', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_program', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', 'Points gagnés'), ('redeem', 'Points utilisés'), ('expire', 'Points expirés'), ('bonus', 'Bonus points')], max_length=20)),
                ('points_amount', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loyalty_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='programmeFidilite.loyaltyprogram')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
