# Generated by Django 5.2.8 on 2025-11-29 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offreDestination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('prix_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('nb_personnes', models.PositiveIntegerField()),
                ('mode_paiement', models.CharField(blank=True, max_length=20, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offreDestination.offre')),
            ],
        ),
    ]
