# Generated by Django 5.2.7 on 2025-12-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='mode_paiement',
            field=models.CharField(choices=[('carte', 'Carte bancaire'), ('espece', 'Espèces'), ('virement', 'Virement')], max_length=20, null=True),
        ),
    ]
