# Generated by Django 5.2.7 on 2025-11-29 22:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_alter_reclamation_client_and_more'),
        ('reservation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='breach_flag',
            field=models.BooleanField(default=False, verbose_name='SLA dépassé ?'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date limite (SLA)'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='priorite',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Faible'), (2, 'Moyenne'), (3, 'Haute')], default=1),
        ),
        migrations.CreateModel(
            name='HistoricalReclamation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type_de_reclamation', models.CharField(max_length=255, verbose_name='Sujet de réclamation')),
                ('description', models.TextField()),
                ('priorite', models.PositiveSmallIntegerField(choices=[(1, 'Faible'), (2, 'Moyenne'), (3, 'Haute')], default=1)),
                ('status', models.CharField(choices=[('en_progression', 'En progression'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='en_progression', max_length=20)),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Date limite (SLA)')),
                ('breach_flag', models.BooleanField(default=False, verbose_name='SLA dépassé ?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reservation.reservation')),
            ],
            options={
                'verbose_name': 'historical reclamation',
                'verbose_name_plural': 'historical reclamations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
