# Generated by Django 5.2.8 on 2025-12-03 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offreDestination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('offer', 'Offre'), ('destination', 'Destination'), ('hebergement', 'Hébergement')], default='offer', max_length=20)),
                ('match_score', models.FloatField(help_text='Score de correspondance avec les préférences (0-100)')),
                ('reason', models.TextField(blank=True, help_text='Raison de la recommandation')),
                ('preference_match', models.FloatField(default=0, help_text='Score correspondance préférences')),
                ('price_match', models.FloatField(default=0, help_text='Score correspondance prix')),
                ('tier_bonus', models.FloatField(default=0, help_text='Bonus selon le tier')),
                ('popularity_score', models.FloatField(default=0, help_text='Score de popularité')),
                ('is_viewed', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('booked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='offreDestination.destination')),
                ('hebergement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='offreDestination.hebergement')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='offreDestination.offre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('relevant', 'Pertinent'), ('not_relevant', 'Non pertinent'), ('already_visited', 'Déjà visité'), ('interested', 'Intéressé')], max_length=20)),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Note de 1 à 5', null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recommandation.recommendation')),
            ],
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', '-match_score'], name='recommandat_user_id_3098c5_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'is_active'], name='recommandat_user_id_4b3c46_idx'),
        ),
    ]
