# Generated by Django 5.2.8 on 2025-12-03 00:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_class', models.CharField(choices=[('ECONOMY', 'Economy'), ('BUSINESS', 'Business'), ('FIRST_CLASS', 'First Class')], default='ECONOMY', max_length=20)),
                ('meal_preference', models.CharField(choices=[('VEGETARIAN', 'Vegetarian'), ('NON_VEGETARIAN', 'Non-Vegetarian'), ('VEGAN', 'Vegan')], default='NON_VEGETARIAN', max_length=20)),
                ('seat_preference', models.CharField(choices=[('AISLE', 'Aisle'), ('WINDOW', 'Window'), ('MIDDLE', 'Middle')], default='AISLE', max_length=20)),
                ('price_range', models.CharField(choices=[('BUDGET', 'Budget'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], default='STANDARD', max_length=20)),
                ('minimum_star_rating', models.PositiveIntegerField(default=3, help_text='Preferred minimum star rating (1-5)', validators=[django.core.validators.MinValueValidator(1, message='Star rating must be at least 1'), django.core.validators.MaxValueValidator(5, message='Star rating cannot exceed 5')])),
                ('special_notes', models.TextField(blank=True, help_text='Any other recurring special requests or preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
