# Generated by Django 5.2.8 on 2025-11-29 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_destination', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('saison', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='destinations/')),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('prix_par_personne', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='offres/')),
                ('actif', models.BooleanField(default=True)),
                ('nom_destinations', models.ManyToManyField(related_name='offres', to='offreDestination.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_hebergement', models.CharField(max_length=150)),
                ('type_hebergement', models.CharField(choices=[('hotel', 'Hôtel'), ('villa', 'Villa'), ('appartement', 'Appartement'), ('auberge', 'Auberge'), ('resort', 'Resort')], max_length=20)),
                ('prix_par_nuit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etoiles', models.PositiveIntegerField(default=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hebergements/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hebergements', to='offreDestination.destination')),
                ('offres', models.ManyToManyField(blank=True, related_name='hebergements', to='offreDestination.offre')),
            ],
        ),
    ]
