# Generated by Django 5.2.7 on 2025-11-29 22:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_offer_alter_feedback_user'),
        ('offreDestination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='note',
        ),
        migrations.AddField(
            model_name='feedback',
            name='note_hebergement',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Hébergement (0-5)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='note_service',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Qualité Service (0-5)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='note_transport',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Transport (0-5)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='note_valeur',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Rapport Qualité/Prix (0-5)'),
        ),
        migrations.CreateModel(
            name='HistoricalFeedback',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('note_service', models.PositiveSmallIntegerField(default=0, verbose_name='Qualité Service (0-5)')),
                ('note_hebergement', models.PositiveSmallIntegerField(default=0, verbose_name='Hébergement (0-5)')),
                ('note_transport', models.PositiveSmallIntegerField(default=0, verbose_name='Transport (0-5)')),
                ('note_valeur', models.PositiveSmallIntegerField(default=0, verbose_name='Rapport Qualité/Prix (0-5)')),
                ('date_soumission', models.DateTimeField(blank=True, editable=False)),
                ('description', models.TextField(blank=True)),
                ('attachement', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='offreDestination.offre', verbose_name='offre')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical feedback',
                'verbose_name_plural': 'historical feedbacks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
