# Generated by Django 5.2.8 on 2025-11-29 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_feedback_note_feedback_note_hebergement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='note_transport',
        ),
        migrations.RemoveField(
            model_name='historicalfeedback',
            name='note_transport',
        ),
    ]
